# References:
# - http://about.travis-ci.org/docs/user/languages/python/
# - http://docs.travis-ci.com/user/docker/
language: python
cache: pip

sudo: required
services:
  - docker

before_install:
  - docker build -t ssato/fleure -f pkg/Dockerfile .
  # - docker info

script:
  - docker run ssato/fleure /bin/sh -c "cd /tmp/fleure && WITH_COVERAGE=1 bash -x ./pkg/runtest.sh"

#after_success:
#  - cd /tmp/fleure && coveralls

notifications:
  email:
    #on_success: always # default: change
    on_failure: always
